name: pack-linux-dashboard

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODE_NAME: SystemDashboard # 定义文件名 
    
    steps:
    # 签出代码
    - uses: actions/checkout@v4
    
    - name: 设置Docker
      run: |
        docker pull debian:buster
        docker create --name builder debian:buster
        docker cp . builder:/app
    
    - name: 在Docker中构建应用
      run: |
        docker exec builder bash -c "cd /app && \
          apt-get update && \
          apt-get install -y python3 python3-pip && \
          python3 -m pip install --upgrade pip && \
          python3 -m pip install pyinstaller==5.13.2 && \
          python3 -m pip install textual psutil && \
          pyinstaller -F dashboard.py \
            --name \"${{ env.CODE_NAME }}\" \
            --clean \
            --runtime-tmpdir /tmp"
    
    - name: 从Docker容器中复制构建结果
      run: |
        docker cp builder:/app/dist .
        ls -la dist
    
    - name: 上传可执行文件
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CODE_NAME }}
        path: dist/${{ env.CODE_NAME }}